---
- name: Set up closest mirror autoselect (ubuntu only)
  template: src=apt_sources.list.j2 dest=/etc/apt/sources.list
  when: ansible_distribution == 'Ubuntu'

- name: Update apt cache
  apt: update_cache=yes

- name: Upgrade all safe packages
  apt: upgrade=safe

- name: install packages
  apt: name={{ item }} update_cache=yes
  with_items:
    - zsh
    - vim
    - ufw
    - monit
    - logwatch
    - collectd
    - htop
    - git
    - fail2ban
    - build-essential
    - sudo
    - unattended-upgrades
    - supervisor
    - apticron
    - apt-transport-https
    - python-software-properties
    - screen
    - curl
    - wget
    - tree

- name: timezone - configure /etc/timezone
  copy:
    content: "{{ common_timezone | regex_replace('$', '\n') }}"
    dest: /etc/timezone
    owner: root
    group: root
    mode: 0644
  register: common_timezone_config

- name: timezone - Set localtime to UTC
  file: src=/usr/share/zoneinfo/Etc/UTC dest=/etc/localtime
  when: common_timezone_config.changed

- name: timezone - reconfigure tzdata
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when: common_timezone_config.changed

- name: Apticron email configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf

- include: users.yml
- include: ufw.yml
- include: security.yml
- include: ntp.yml
