---
# Installs and configures ufw, which in turn uses iptables for firewall management

# ufw includes sensible icmp defaults
- name: Install ufw
  apt: pkg=ufw state=present

- name: Deny everything
  ufw: policy=deny
  tags:
    - config

- name: Set firewall rule for DNS
  ufw: rule=allow port=domain
  tags:
    - config

- name: Set firewall rules for web traffic and SSH
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - http
    - https
    - ssh
  tags:
    - config

- name: Set firewall rules for user defined tcp ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items: "{{ ufw_allowed_ports_tcp }}"
  tags:
    - config

- name: Set firewall rules for user defined udp ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items: "{{ ufw_allowed_ports_udp }}"
  tags:
    - config

- name: Enable UFW
  ufw: state=enabled
  tags:
    - config

- name: Check config of ufw
  command: cat /etc/ufw/ufw.conf
  register: ufw_config
  changed_when: False  # never report as "changed"

- name: Disable logging (workaround for known bug in Debian 7)
  ufw: logging=off
  when: "ansible_lsb['codename'] == 'wheezy' and 'LOGLEVEL=off' not in ufw_config.stdout"
  tags:
    - config
